# Basic Python

## 1. Split this string

In [3]:
s = "Hi there Sam!"
s.split(" ")

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [5]:
planet = "Earth"
diameter = 12742
print("The diameter of {} is {} kilometers.".format(planet,diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [8]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [5]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [6]:
array1=np.zeros(10)
print(array1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
array2=np.ones(10)*5
print(array2)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [9]:
array3=np.arange(20,36,2)
print(array3)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
array4=np.arange(0,9).reshape(3,3)
print(array4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [12]:
import pandas as pd


In [13]:
data = {'Name':['EVA', 'SAM', 'PARVEEN', 'JACK'], 'Age':[21, 22, 28, 35]}
df = pd.DataFrame(data)
print(df)

      Name  Age
0      EVA   21
1      SAM   22
2  PARVEEN   28
3     JACK   35


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [14]:
d = pd.date_range(start='1/1/2023', end='10/2/2023', freq='MS')    
print(d)

DatetimeIndex(['2023-01-01', '2023-02-01', '2023-03-01', '2023-04-01',
               '2023-05-01', '2023-06-01', '2023-07-01', '2023-08-01',
               '2023-09-01', '2023-10-01'],
              dtype='datetime64[ns]', freq='MS')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [15]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [16]:
u=pd.DataFrame(lists)
print(u)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
